### ISSUE TITLE
Instructions

### ISSUE THREAD

**Issue by coolpalani** [bjgillet/CloudForms-Automation-Bricks#1]
Please add a instruction for how to import domain,dialogues in CloudForm/Manageiq

**Comment by bjgillet** [comment]
Hi coolpalani,
There are currently no dialogs within AutomationBricks.
To import the AutomationBricks domain, just grab the AutomationBricks.zip domain. From CloudForms or ManageIQ, select Automate/Import-export (CF4.2 or prior), Automation/Automate/Import-export (4.5 or later).
Browse to the place you downloaded the .zip file, then select the full AutomationBricks components and import. Your new domain could be disabled at initial time, so think to check and enable it if necessary.
I am currently working on a doc that should arrive as soon I will have some time for it.
Usage of CustomStateMachines is somewhat documented in the code but there is far more to add.
Hope this helps...
Bruno.

**Comment by bjgillet** [comment]
Shortly updated README.md to address the point.
